addons:
  apt:
    packages:
      - python-pygments

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

deploy:
  provider: s3                # Use the S3 provider
  skip_cleanup: true          # Don't remove the output files of our builds, the provider needs them to deploy
  bucket: jongerius-solutions # S3 bucket used
  acl: public_read            # Yup it's a website
  local_dir: public # Hugo output will be found here
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: deploy
